name: Python CI

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "requirements.txt"
      - ".github/workflows/python-tests.yml"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: 
        export PYTHONPATH=$PWD:$PYTHONPATH
        pytest tests/
